"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import Script from "next/script";
import { useEffect } from "react";

const interSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Trikona",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    dataLayer: unknown[];
    gtag: (...args: unknown[]) => void;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  function Analytics() {
    useEffect(() => {
      window.dataLayer = window.dataLayer || [];

      function gtag(...args: unknown[]) {
        window.dataLayer.push(args);
      }

      window.gtag = gtag;

      window.gtag("js", new Date());
      window.gtag("config", "G-D2CEW60P40");
    }, []);

    return null;
  }
  return (
    <html lang="en" className="flex justify-center scroll-smooth bg-[#F5F5F5]">
      <body
        className={`${interSans.variable} max-w-[1520px] bg-[#F5F5F5] px-5 antialiased max-lg:px-0`}
      >
        <ToastContainer />
        <Header />
        {children}
        <Footer />
        <Analytics />
      </body>
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-D2CEW60P40"
      ></Script>
      <Script strategy="afterInteractive" id="google-analytics">
        {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-D2CEW60P40');`}
      </Script>
    </html>
  );
}
