import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  subsets: ["latin"],
  variable: "--font-inter", 
});


export const metadata: Metadata = {
  title: "Trikona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#F5F5F5] flex justify-center scroll-smooth">
      <body
        className={`${interSans.variable}  antialiased w-[1520px]`}
      >
        {children}
      </body>
    </html>
  );
}
